version: '3.8'
services:
  api:
    build: .
    container_name: real_estate_api
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

